# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints_fc_64.xdc

# Block Designs: bd/FC_64_bd/FC_64_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd || ORIG_REF_NAME==FC_64_bd} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_FC_64_IP_0_0/FC_64_bd_FC_64_IP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_FC_64_IP_0_0 || ORIG_REF_NAME==FC_64_bd_FC_64_IP_0_0} -quiet] -quiet

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_FC_64_IP_0_0/6b0a/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_FC_64_IP_0_0/f23e/mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult || ORIG_REF_NAME==mult} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_zynq_ultra_ps_e_0_0/FC_64_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==FC_64_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_axi_bram_ctrl_0_0/FC_64_bd_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_axi_bram_ctrl_0_0 || ORIG_REF_NAME==FC_64_bd_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_blk_mem_gen_0_0/FC_64_bd_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_blk_mem_gen_0_0 || ORIG_REF_NAME==FC_64_bd_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_axi_bram_ctrl_1_0/FC_64_bd_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_axi_bram_ctrl_1_0 || ORIG_REF_NAME==FC_64_bd_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_axi_bram_ctrl_2_0/FC_64_bd_axi_bram_ctrl_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_axi_bram_ctrl_2_0 || ORIG_REF_NAME==FC_64_bd_axi_bram_ctrl_2_0} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_blk_mem_gen_1_0/FC_64_bd_blk_mem_gen_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_blk_mem_gen_1_0 || ORIG_REF_NAME==FC_64_bd_blk_mem_gen_1_0} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_blk_mem_gen_2_0/FC_64_bd_blk_mem_gen_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_blk_mem_gen_2_0 || ORIG_REF_NAME==FC_64_bd_blk_mem_gen_2_0} -quiet] -quiet

# IP: bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/FC_64_bd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_axi_smc_0 || ORIG_REF_NAME==FC_64_bd_axi_smc_0} -quiet] -quiet

# Block Designs: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/bd_2f3d.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_0/bd_2f3d_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_1/bd_2f3d_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_2/bd_2f3d_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_3/bd_2f3d_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_4/bd_2f3d_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_5/bd_2f3d_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_6/bd_2f3d_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_7/bd_2f3d_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_8/bd_2f3d_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_9/bd_2f3d_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_10/bd_2f3d_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_11/bd_2f3d_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_12/bd_2f3d_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_13/bd_2f3d_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_14/bd_2f3d_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_15/bd_2f3d_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_16/bd_2f3d_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_17/bd_2f3d_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_18/bd_2f3d_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_19/bd_2f3d_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_20/bd_2f3d_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_21/bd_2f3d_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_22/bd_2f3d_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_23/bd_2f3d_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_24/bd_2f3d_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_25/bd_2f3d_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_26/bd_2f3d_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_27/bd_2f3d_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_28/bd_2f3d_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_29/bd_2f3d_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_30/bd_2f3d_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_31/bd_2f3d_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_32/bd_2f3d_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_33/bd_2f3d_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_34/bd_2f3d_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_35/bd_2f3d_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_36/bd_2f3d_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_37/bd_2f3d_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_38/bd_2f3d_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_39/bd_2f3d_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_40/bd_2f3d_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_41/bd_2f3d_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_42/bd_2f3d_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_43/bd_2f3d_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_44/bd_2f3d_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_45/bd_2f3d_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_46/bd_2f3d_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_47/bd_2f3d_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_48/bd_2f3d_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_49/bd_2f3d_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_50/bd_2f3d_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_51/bd_2f3d_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_52/bd_2f3d_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/FC_64_bd/ip/FC_64_bd_rst_ps8_0_96M_0/FC_64_bd_rst_ps8_0_96M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FC_64_bd_rst_ps8_0_96M_0 || ORIG_REF_NAME==FC_64_bd_rst_ps8_0_96M_0} -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_FC_64_IP_0_0/6b0a/ila_v6_2/constraints/ila.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_FC_64_IP_0_0/6b0a/ila_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_zynq_ultra_ps_e_0_0/FC_64_bd_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_zynq_ultra_ps_e_0_0/FC_64_bd_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FC_64_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==FC_64_bd_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_blk_mem_gen_0_0/FC_64_bd_blk_mem_gen_0_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_blk_mem_gen_1_0/FC_64_bd_blk_mem_gen_1_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_blk_mem_gen_2_0/FC_64_bd_blk_mem_gen_2_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_1/bd_2f3d_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_1/bd_2f3d_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_2/bd_2f3d_arsw_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_3/bd_2f3d_rsw_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_4/bd_2f3d_awsw_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_5/bd_2f3d_wsw_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_6/bd_2f3d_bsw_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_10/bd_2f3d_s00a2s_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_11/bd_2f3d_sarn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_11/bd_2f3d_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_12/bd_2f3d_srn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_12/bd_2f3d_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_13/bd_2f3d_sawn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_13/bd_2f3d_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_14/bd_2f3d_swn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_14/bd_2f3d_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_15/bd_2f3d_sbn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_15/bd_2f3d_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_19/bd_2f3d_s01a2s_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_20/bd_2f3d_sarn_1_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_20/bd_2f3d_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_21/bd_2f3d_srn_1_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_21/bd_2f3d_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_22/bd_2f3d_sawn_1_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_22/bd_2f3d_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_23/bd_2f3d_swn_1_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_23/bd_2f3d_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_24/bd_2f3d_sbn_1_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_24/bd_2f3d_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_25/bd_2f3d_m00s2a_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_26/bd_2f3d_m00arn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_26/bd_2f3d_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_27/bd_2f3d_m00rn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_27/bd_2f3d_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_28/bd_2f3d_m00awn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_28/bd_2f3d_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_29/bd_2f3d_m00wn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_29/bd_2f3d_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_30/bd_2f3d_m00bn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_30/bd_2f3d_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_32/bd_2f3d_m01s2a_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_33/bd_2f3d_m01arn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_33/bd_2f3d_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_34/bd_2f3d_m01rn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_34/bd_2f3d_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_35/bd_2f3d_m01awn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_35/bd_2f3d_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_36/bd_2f3d_m01wn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_36/bd_2f3d_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_37/bd_2f3d_m01bn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_37/bd_2f3d_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_39/bd_2f3d_m02s2a_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_40/bd_2f3d_m02arn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_40/bd_2f3d_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_41/bd_2f3d_m02rn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_41/bd_2f3d_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_42/bd_2f3d_m02awn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_42/bd_2f3d_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_43/bd_2f3d_m02wn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_43/bd_2f3d_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_44/bd_2f3d_m02bn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_44/bd_2f3d_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_46/bd_2f3d_m03s2a_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_47/bd_2f3d_m03arn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_47/bd_2f3d_m03arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_48/bd_2f3d_m03rn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_48/bd_2f3d_m03rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_49/bd_2f3d_m03awn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_49/bd_2f3d_m03awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_50/bd_2f3d_m03wn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_50/bd_2f3d_m03wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_51/bd_2f3d_m03bn_0_ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/bd_0/ip/ip_51/bd_2f3d_m03bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/ooc.xdc

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FC_64_bd_axi_smc_0 || ORIG_REF_NAME==FC_64_bd_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_rst_ps8_0_96M_0/FC_64_bd_rst_ps8_0_96M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FC_64_bd_rst_ps8_0_96M_0 || ORIG_REF_NAME==FC_64_bd_rst_ps8_0_96M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/ip/FC_64_bd_rst_ps8_0_96M_0/FC_64_bd_rst_ps8_0_96M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==FC_64_bd_rst_ps8_0_96M_0 || ORIG_REF_NAME==FC_64_bd_rst_ps8_0_96M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/FC_64/FC_64.gen/sources_1/bd/FC_64_bd/FC_64_bd_ooc.xdc
