vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xilinx_vip
vlib questa_lib/msim/xpm
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/axi_vip_v1_1_17
vlib questa_lib/msim/zynq_ultra_ps_e_vip_v1_0_17
vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/xbip_utils_v3_0_13
vlib questa_lib/msim/xbip_pipe_v3_0_9
vlib questa_lib/msim/xbip_bram18k_v3_0_9
vlib questa_lib/msim/mult_gen_v12_0_21
vlib questa_lib/msim/xlconstant_v1_1_9
vlib questa_lib/msim/lib_cdc_v1_0_3
vlib questa_lib/msim/proc_sys_reset_v5_0_15
vlib questa_lib/msim/smartconnect_v1_0
vlib questa_lib/msim/axi_register_slice_v2_1_31
vlib questa_lib/msim/gigantic_mux
vlib questa_lib/msim/xlconcat_v2_1_6

vmap xilinx_vip questa_lib/msim/xilinx_vip
vmap xpm questa_lib/msim/xpm
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap axi_vip_v1_1_17 questa_lib/msim/axi_vip_v1_1_17
vmap zynq_ultra_ps_e_vip_v1_0_17 questa_lib/msim/zynq_ultra_ps_e_vip_v1_0_17
vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap xbip_utils_v3_0_13 questa_lib/msim/xbip_utils_v3_0_13
vmap xbip_pipe_v3_0_9 questa_lib/msim/xbip_pipe_v3_0_9
vmap xbip_bram18k_v3_0_9 questa_lib/msim/xbip_bram18k_v3_0_9
vmap mult_gen_v12_0_21 questa_lib/msim/mult_gen_v12_0_21
vmap xlconstant_v1_1_9 questa_lib/msim/xlconstant_v1_1_9
vmap lib_cdc_v1_0_3 questa_lib/msim/lib_cdc_v1_0_3
vmap proc_sys_reset_v5_0_15 questa_lib/msim/proc_sys_reset_v5_0_15
vmap smartconnect_v1_0 questa_lib/msim/smartconnect_v1_0
vmap axi_register_slice_v2_1_31 questa_lib/msim/axi_register_slice_v2_1_31
vmap gigantic_mux questa_lib/msim/gigantic_mux
vmap xlconcat_v2_1_6 questa_lib/msim/xlconcat_v2_1_6

vlog -work xilinx_vip  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm  -93  \
"D:/GiaPhuc/Vivado/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_17  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/4d04/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work zynq_ultra_ps_e_vip_v1_0_17  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_zynq_ultra_ps_e_0_0/sim/SoC_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/sim/ila_top.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/sim/ila_module.v" \

vcom -work xbip_utils_v3_0_13  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/mult/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

vcom -work xbip_pipe_v3_0_9  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/mult/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

vcom -work xbip_bram18k_v3_0_9  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/mult/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \

vcom -work mult_gen_v12_0_21  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/mult/hdl/mult_gen_v12_0_vh_rfs.vhd" \

vcom -work xil_defaultlib  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/mult/sim/mult.vhd" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/sim/ila_test.v" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/BUF_group.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/adder.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/adder_tree_16.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/controller.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/data_buffer.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/datapath.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/fxp_mult.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/ping_pong_buffer.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/process_unit.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/pu_array.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/top_design.sv" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src/MY_IP.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/sim/SoC_MY_IP_0_0.v" \

vlog -work xlconstant_v1_1_9  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_0/sim/bd_d7be_one_0.v" \

vcom -work lib_cdc_v1_0_3  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work proc_sys_reset_v5_0_15  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_1/sim/bd_d7be_psr_aclk_0.vhd" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_2/sim/bd_d7be_arsw_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_3/sim/bd_d7be_rsw_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_4/sim/bd_d7be_awsw_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_5/sim/bd_d7be_wsw_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_6/sim/bd_d7be_bsw_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/98d8/hdl/sc_mmu_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_7/sim/bd_d7be_s00mmu_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_8/sim/bd_d7be_s00tr_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/a950/hdl/sc_si_converter_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_9/sim/bd_d7be_s00sic_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_10/sim/bd_d7be_s00a2s_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/sc_node_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_11/sim/bd_d7be_sarn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_12/sim/bd_d7be_srn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_13/sim/bd_d7be_sawn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_14/sim/bd_d7be_swn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_15/sim/bd_d7be_sbn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_16/sim/bd_d7be_s01mmu_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_17/sim/bd_d7be_s01tr_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_18/sim/bd_d7be_s01sic_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_19/sim/bd_d7be_s01a2s_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_20/sim/bd_d7be_sarn_1.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_21/sim/bd_d7be_srn_1.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_22/sim/bd_d7be_sawn_1.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_23/sim/bd_d7be_swn_1.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_24/sim/bd_d7be_sbn_1.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_25/sim/bd_d7be_m00s2a_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_26/sim/bd_d7be_m00arn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_27/sim/bd_d7be_m00rn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_28/sim/bd_d7be_m00awn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_29/sim/bd_d7be_m00wn_0.sv" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_30/sim/bd_d7be_m00bn_0.sv" \

vlog -work smartconnect_v1_0  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/1f04/hdl/sc_exit_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -incr -mfcu  -sv -L axi_vip_v1_1_17 -L smartconnect_v1_0 -L zynq_ultra_ps_e_vip_v1_0_17 -L xilinx_vip "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/ip/ip_31/sim/bd_d7be_m00e_0.sv" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/bd_0/sim/bd_d7be.v" \

vlog -work axi_register_slice_v2_1_31  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/92b2/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_axi_smc_0/sim/SoC_axi_smc_0.v" \

vcom -work xil_defaultlib  -93  \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_rst_ps8_0_99M_0/sim/SoC_rst_ps8_0_99M_0.vhd" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_0/sim/bd_5c78_ila_lib_0.v" \

vlog -work gigantic_mux  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/7215/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_1/bd_5c78_g_inst_0_gigantic_mux.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_1/sim/bd_5c78_g_inst_0.v" \

vlog -work xlconcat_v2_1_6  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ipshared/6120/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -incr -mfcu  "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/ec67/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/a317/hdl" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/6138" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/f0b6/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/c783/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_top/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/src/ila_module/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_MY_IP_0_0/tmp_edit_project.srcs/sources_1/ip/ila_test/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2f94/src" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/814a/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/1017/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/8745/hdl/verilog" "+incdir+../../../../SoC.gen/sources_1/bd/SoC/ipshared/2340/hdl/verilog" "+incdir+D:/GiaPhuc/Vivado/Vivado/2024.1/data/xilinx_vip/include" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_2/sim/bd_5c78_slot_0_aw_0.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_3/sim/bd_5c78_slot_0_w_0.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_4/sim/bd_5c78_slot_0_b_0.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_5/sim/bd_5c78_slot_0_ar_0.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/ip/ip_6/sim/bd_5c78_slot_0_r_0.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/bd_0/sim/bd_5c78.v" \
"../../../../SoC.gen/sources_1/bd/SoC/ip/SoC_system_ila_0_0/sim/SoC_system_ila_0_0.v" \
"../../../../SoC.gen/sources_1/bd/SoC/sim/SoC.v" \

vlog -work xil_defaultlib \
"glbl.v"

