# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons_axi.xdc

# IP: ip/ila_top/ila_top.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_top || ORIG_REF_NAME==ila_top} -quiet] -quiet

# IP: ip/mult/mult.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult || ORIG_REF_NAME==mult} -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/AXI_MY_IP/project_1/project_1.gen/sources_1/ip/ila_top/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_top || ORIG_REF_NAME==ila_top} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/AXI_MY_IP/project_1/project_1.gen/sources_1/ip/ila_top/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ila_top || ORIG_REF_NAME==ila_top} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/GiaPhuc/Project_1/Dense_0/AXI_MY_IP/project_1/project_1.gen/sources_1/ip/ila_top/ila_top_ooc.xdc
