create_clock -period 10.000 [get_ports clk]
#set_clock_latency -max 1.5 [get_clocks clk]

#set_input_delay -clock [get_clocks clk] -max 6.000 [get_ports nreset]
#set_input_delay -clock [get_clocks clk] -max 6.000 [get_ports we_data]
#set_input_delay -clock [get_clocks clk] -max 6.000 [get_ports we_bias]
#set_input_delay -clock [get_clocks clk] -max 6.000 [get_ports we_weight]
#set_input_delay -clock [get_clocks clk] -max 6.000 [get_ports input_data]
#set_input_delay -clock [get_clocks clk] -max 6.000 [get_ports input_bias]
#set_input_delay -clock [get_clocks clk] -max 6.000 [get_ports input_weight]
#set_output_delay -clock [get_clocks clk] -max 5.000 [get_ports neuron_out]
#set_output_delay -clock [get_clocks clk] -max 5.000 [get_ports neuron_done]

#set_input_delay -clock [get_clocks clk] -min 3.500 [get_ports nreset]
#set_input_delay -clock [get_clocks clk] -min 3.500 [get_ports we_data]
#set_input_delay -clock [get_clocks clk] -min 3.500 [get_ports we_bias]
#set_input_delay -clock [get_clocks clk] -min 3.500 [get_ports we_weight]
#set_input_delay -clock [get_clocks clk] -min 3.500 [get_ports input_data]
#set_input_delay -clock [get_clocks clk] -min 3.500 [get_ports input_bias]
#set_input_delay -clock [get_clocks clk] -min 3.500 [get_ports input_weight]
#set_output_delay -clock [get_clocks clk] -min 3.000 [get_ports neuron_out]
#set_output_delay -clock [get_clocks clk] -min 3.000 [get_ports neuron_done]

set_property PACKAGE_PIN AE10 [get_ports neuron_done]
#////////////////////////////LVCMOS18///////////////////////////////
#set_property IOSTANDARD LVCMOS18 [get_ports clk]
#set_property IOSTANDARD LVCMOS18 [get_ports nreset]
#set_property IOSTANDARD LVCMOS18 [get_ports we_data]
#set_property IOSTANDARD LVCMOS18 [get_ports we_bias]
#set_property IOSTANDARD LVCMOS18 [get_ports we_weight]
#set_property IOSTANDARD LVCMOS18 [get_ports neuron_done]

#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[8]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[9]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[10]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[11]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[12]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[13]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[14]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[15]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[16]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[17]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[18]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[19]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[20]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[21]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[22]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[23]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[24]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[25]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[26]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[27]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[28]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[29]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[30]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_data[31]}]

#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[8]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[9]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[10]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[11]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[12]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[13]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[14]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[15]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[16]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[17]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[18]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[19]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[20]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[21]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[22]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[23]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[24]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[25]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[26]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[27]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[28]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[29]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[30]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_bias[31]}]

#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[8]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[9]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[10]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[11]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[12]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[13]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[14]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[15]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[16]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[17]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[18]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[19]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[20]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[21]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[22]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[23]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[24]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[25]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[26]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[27]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[28]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[29]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[30]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {input_weight[31]}]

#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[0]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[1]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[2]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[3]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[4]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[5]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[6]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[7]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[8]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[9]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[10]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[11]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[12]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[13]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[14]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[15]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[16]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[17]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[18]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[19]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[20]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[21]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[22]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[23]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[24]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[25]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[26]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[27]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[28]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[29]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[30]}]
#set_property IOSTANDARD LVCMOS18 [get_ports {neuron_out[31]}]




